<a href="https://colab.research.google.com/github/satyamnewale/basic-NLP/blob/main/pytorch-basicipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
print(torch.__version__)


2.9.0+cu126


Create a Tensor


In [4]:
# using empty
a = torch.empty(2,3)
print(a)
print(type(a),a.shape)

tensor([[4.2528e-32, 0.0000e+00, 2.1740e+05],
        [4.4264e-41, 4.4842e-44, 0.0000e+00]])
<class 'torch.Tensor'> torch.Size([2, 3])


In [6]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
#using random with manual seed
torch.manual_seed(0)
torch.rand(2,3)

tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341]])

In [9]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [29]:
#one_like
print(torch.ones_like(torch.tensor([[1,2,3],[4,5,6]])))

#zero_like
print(torch.zeros_like(torch.tensor([[1,2,3],[4,5,6]])))

#rand_like
print(torch.rand_like(torch.tensor([[1,2,3],[4,5,6]]), dtype = torch.float32))

tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[0.4901, 0.8964, 0.4556],
        [0.6323, 0.3489, 0.4017]])


In [11]:
#other ways

#arange
print(f"arange -> {torch.arange(0,10,2)}")

#using linspace
print(f"linspace -> {torch.linspace(0,10,5)}")

#using eye
print(f"eye -> {torch.eye(3,4)}")

# using full
print(f"full -> {torch.full((2,3),2)}")


arange -> tensor([0, 2, 4, 6, 8])
linspace -> tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
eye -> tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])
full -> tensor([[2, 2, 2],
        [2, 2, 2]])


In [22]:
#Tensor shape

x = torch.tensor([[1,2,3],[4,5,6]])
print(x.shape)
print(f"strides -> {x.stride()}, byte-size -> {x.element_size()}")
print(f"dtype -> {x.dtype}, device -> {x.device}")

y = x[:,[0,2]]
print(x.storage().data_ptr() == y.storage().data_ptr()) #false means copy
print(f"y -> {y}, strides -> {y.stride()}")

torch.Size([2, 3])
strides -> (3, 1), byte-size -> 8
dtype -> torch.int64, device -> cpu
False
y -> tensor([[1, 3],
        [4, 6]]), strides -> (2, 1)


/tmp/ipython-input-2641425665.py:9: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  print(x.storage().data_ptr() == y.storage().data_ptr())


Mathematical operation
---

In [39]:
# scalar operations
a = torch.tensor([[1,2],[2,4]])

print(f"a+1 -> {a+1}")
print(f"a*2 -> {a*2}")
print(f"a**2 -> {a**2}")
print(f"a/2 -> {a/2}")
print(f"a//2 -> {a//2}")
print(f"a%2 -> {a%2}")

# element wise between two tensors

b = torch.rand([2,3])
c = torch.rand([2,3])

print(f"b + c -> {b + c}")
print(f"b * c -> {b * c}")
print(f"b ** c -> {b ** c}")
print(f"b / c -> {b / c}")
print(f"b // c -> {b // c}")
print(f"b % c -> {b % c}")

# simgle tensor element wise operations
print(f"b.exp() -> {b.exp()}")
print(f"b.log() -> {b.log()}")
print(f"b.sqrt() -> {b.sqrt()}")
print(f"b.sin() -> {b.sin()}")
print(f"b.cos() -> {b.cos()}")
print(f"b.abs() -> {torch.abs(b)}")
print(f"neg -> {b.neg()}")
print(f"b.ceil() -> {b.ceil()}")
print(f"b.floor() -> {b.floor()}")
print(f"b.round() -> {b.round()}")

#clamp
print(f"torch.clamp([[1,3,4],[3,5,1]],2,4) -> {torch.clamp(torch.tensor([[1,3,4],[3,5,1]]),2,4)}")

a+1 -> tensor([[2, 3],
        [3, 5]])
a*2 -> tensor([[2, 4],
        [4, 8]])
a**2 -> tensor([[ 1,  4],
        [ 4, 16]])
a/2 -> tensor([[0.5000, 1.0000],
        [1.0000, 2.0000]])
a//2 -> tensor([[0, 1],
        [1, 2]])
a%2 -> tensor([[1, 0],
        [0, 0]])
b + c -> tensor([[1.3151, 0.6534, 0.6708],
        [1.3193, 0.7687, 1.5723]])
b * c -> tensor([[0.3981, 0.0451, 0.1109],
        [0.4163, 0.1121, 0.5899]])
b ** c -> tensor([[0.5316, 0.9576, 0.6324],
        [0.8880, 0.3928, 0.9711]])
b / c -> tensor([[0.5607, 7.3390, 0.7861],
        [1.5246, 0.3416, 1.5417]])
b // c -> tensor([[0., 7., 0.],
        [1., 0., 1.]])
b % c -> tensor([[0.4725, 0.0266, 0.2952],
        [0.2741, 0.1957, 0.3351]])
b.exp() -> tensor([[1.6039, 1.7773, 1.3434],
        [2.2182, 1.2162, 2.5953]])
b.log() -> tensor([[-0.7498, -0.5533, -1.2200],
        [-0.2273, -1.6310, -0.0474]])
b.sqrt() -> tensor([[0.6874, 0.7583, 0.5434],
        [0.8926, 0.4424, 0.9766]])
b.sin() -> tensor([[0.4551, 0.5439, 0.291

In [58]:
#reduction
torch.manual_seed(0)
e = torch.randint(size=(2,3),low=0,high=10)
print(e)

print(f"e.sum() -> {e.sum()}")
print(f"e.mean() -> {e.float().mean()}")
print(f"e.max() -> {e.max()}")
print(f"e.min() -> {e.min()}")
print(f"e.prod() -> {e.prod()}")
print(f"e.std() -> {e.float().std()}")
print(f"e.var() -> {e.float().var()}")
print(f"e.median() -> {e.median()}")

#argmax
print(f"e.argmax() -> {e.argmax()}")
print(f"e.argmax(dim=0) -> {e.argmax(dim=0)}")
print(f"e.argmax(dim=1) -> {e.argmax(dim=1)}")

#argmin
print(f"e.argmin() -> {e.argmin()}")
print(f"e.argmin(dim=0) -> {e.argmin(dim=0)}")
print(f"e.argmin(dim=1) -> {e.argmin(dim=1)}")

tensor([[4, 9, 3],
        [0, 3, 9]])
e.sum() -> 28
e.mean() -> 4.666666507720947
e.max() -> 9
e.min() -> 0
e.prod() -> 0
e.std() -> 3.6147844791412354
e.var() -> 13.066666603088379
e.median() -> 3
e.unique(dim = 0 ) -> tensor([[0, 3, 9],
        [4, 9, 3]])
e.argmax() -> 1
e.argmax(dim=0) -> tensor([0, 0, 1])
e.argmax(dim=1) -> tensor([1, 2])
e.argmin() -> 3
e.argmin(dim=0) -> tensor([1, 1, 0])
e.argmin(dim=1) -> tensor([2, 0])


matrix operations

In [59]:
torch.manual_seed(0)
f = torch.rand(size=(2,3))
g = torch.rand(size=(3,4))

In [61]:
# matrix multiplication

print(f"matmul : {torch.matmul(f,g)}")
print(f"mm : {f.mm(g)}")

#transpose
print(f"f : {f}")
print(f"transpose : {torch.transpose(f,0,1)}")

matmul : tensor([[0.5372, 0.7994, 0.3050, 0.5143],
        [0.3583, 0.5706, 0.5094, 0.6427]])
mm : tensor([[0.5372, 0.7994, 0.3050, 0.5143],
        [0.3583, 0.5706, 0.5094, 0.6427]])
f : tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341]])
transpose : tensor([[0.4963, 0.1320],
        [0.7682, 0.3074],
        [0.0885, 0.6341]])


In [70]:
# special functions
import torch.nn.functional as F
torch.manual_seed(0)
h = torch.randint(size = (2,3),low= 0, high = 10, dtype = torch.float32)

# log
print(f"log : {torch.log(h)}")

# exp
print(f"exp : {torch.exp(h)}")

#sqrt
print(f"sqrt : {torch.sqrt(h)}")

#softmax
print(f"softmax : {torch.softmax(h,dim=0)}")

#sigmoid
print(f"sigmoid : {torch.sigmoid(h)}")

#relu
print(f"relu : {torch.relu(h)}")

#leaky relu
print(f"leaky relu : {F.leaky_relu(h)}")

log : tensor([[1.3863, 2.1972, 1.0986],
        [  -inf, 1.0986, 2.1972]])
exp : tensor([[5.4598e+01, 8.1031e+03, 2.0086e+01],
        [1.0000e+00, 2.0086e+01, 8.1031e+03]])
sqrt : tensor([[2.0000, 3.0000, 1.7321],
        [0.0000, 1.7321, 3.0000]])
softmax : tensor([[0.9820, 0.9975, 0.0025],
        [0.0180, 0.0025, 0.9975]])
sigmoid : tensor([[0.9820, 0.9999, 0.9526],
        [0.5000, 0.9526, 0.9999]])
relu : tensor([[4., 9., 3.],
        [0., 3., 9.]])
leaky relu : tensor([[4., 9., 3.],
        [0., 3., 9.]])


Inplace operaion
---

In [71]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(f"m: {m}, n: {n}")
m.add_(n)
print(f"m: {m}, n: {n}")


m: tensor([[0.4901, 0.8964, 0.4556],
        [0.6323, 0.3489, 0.4017]]), n: tensor([[0.0223, 0.1689, 0.2939],
        [0.5185, 0.6977, 0.8000]])
m: tensor([[0.5124, 1.0653, 0.7495],
        [1.1508, 1.0466, 1.2017]]), n: tensor([[0.0223, 0.1689, 0.2939],
        [0.5185, 0.6977, 0.8000]])


tensor operations on GPU
---

In [3]:
torch.cuda.is_available()

True

In [4]:
device = torch.device('cuda')

In [6]:
#create a new tensor on GPU
torch.rand((2,3), device = device)

tensor([[0.0937, 0.0446, 0.7909],
        [0.1849, 0.9596, 0.2167]], device='cuda:0')

In [8]:
#moving existing cpu tensor to gpu
a = torch.rand(2,3)

b= a.to(device)
print(b)

tensor([[0.8999, 0.4545, 0.4996],
        [0.5096, 0.5209, 0.5154]], device='cuda:0')


In [5]:
#cpu vs gpu

import time

#define size matrix
size = 10000

# create random matrices on CPU
matrix_cpu1 = torch.randn(size,size)
matrix_cpu2 = torch.randn(size,size)

# measure time on cpu
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1,matrix_cpu2)
end_time = time.time()
cpu_time = end_time - start_time

print(f"time on cpu: {cpu_time: .4f} sec")

#move matrices to GPU
matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

#measure time on gpu
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1,matrix_gpu2)
end_time = time.time()
gpu_time = end_time - start_time

print(f"time on gpu: {gpu_time: .4f} sec")

time on cpu:  24.8058 sec
time on gpu:  0.1226 sec
