<a href="https://colab.research.google.com/github/satyamnewale/basic-NLP/blob/main/simple-NN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import torch
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


In [43]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [44]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)
df.head()


diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [45]:
df.shape

(569, 31)

In [48]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

In [49]:
#scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [54]:
X_train

array([[-1.04587507, -0.15764237, -1.04919401, ..., -0.76471135,
        -1.0995313 , -0.29762101],
       [ 0.14925699, -0.84465825,  0.04090721, ..., -0.87643885,
        -0.59626465, -1.4469559 ],
       [ 1.87813734, -0.35527708,  1.73896575, ...,  1.12168635,
        -0.24699442,  0.2698196 ],
       ...,
       [-1.23239689, -0.84701104, -1.21216035, ..., -0.76471135,
        -0.64071722,  0.43416325],
       [-0.12051797, -0.69407943, -0.16681153, ..., -0.42468473,
        -0.15808927, -0.32974029],
       [-0.68327432, -1.07993766, -0.65022203, ..., -0.13466202,
        -0.47878284,  0.79282854]])

In [52]:
#label encoder
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [53]:
y_train

array([0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,

In [58]:
#numpy to pytorch tensors
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train.astype(np.float64))
y_test_tensor = torch.from_numpy(y_test.astype(np.float64))

In [59]:
X_train_tensor

tensor([[-1.0459, -0.1576, -1.0492,  ..., -0.7647, -1.0995, -0.2976],
        [ 0.1493, -0.8447,  0.0409,  ..., -0.8764, -0.5963, -1.4470],
        [ 1.8781, -0.3553,  1.7390,  ...,  1.1217, -0.2470,  0.2698],
        ...,
        [-1.2324, -0.8470, -1.2122,  ..., -0.7647, -0.6407,  0.4342],
        [-0.1205, -0.6941, -0.1668,  ..., -0.4247, -0.1581, -0.3297],
        [-0.6833, -1.0799, -0.6502,  ..., -0.1347, -0.4788,  0.7928]],
       dtype=torch.float64)

In [79]:
#defining the model

class MySimpleNN():

  def __init__(self, X):
    self.weights = torch.rand(X.shape[1],1, dtype = torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype = torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    ## clamps prediction to avoid log(0) and log(1)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
    ## calculate loss
    loss = (-(y*torch.log(y_pred) + (1-y)*torch.log(1-y_pred))).mean()
    return loss

In [86]:
#important parameters

learning_rate = 0.1
epochs = 250

In [87]:
#training pipeline
## create model
model = MySimpleNN(X_train_tensor)

## loop
for epoch in range(epochs):

  ## forward pass
  y_pred = model.forward(X_train_tensor)

  ## loss
  loss = model.loss_function(y_pred, y_train_tensor)

  ## backward pass
  loss.backward()

  #now update weights and bias
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad # Corrected line

  #zero gradient
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  #loss for each epoch
  print(f'Epoch: {epoch + 1} Loss: {loss.item()}')

Epoch: 1 Loss: 3.32682865959836
Epoch: 2 Loss: 3.1901654813147506
Epoch: 3 Loss: 3.050441293225118
Epoch: 4 Loss: 2.9112150504053953
Epoch: 5 Loss: 2.7720857194371913
Epoch: 6 Loss: 2.6319202236670343
Epoch: 7 Loss: 2.4893972927400214
Epoch: 8 Loss: 2.3420186329392583
Epoch: 9 Loss: 2.194752113703067
Epoch: 10 Loss: 2.048102740304187
Epoch: 11 Loss: 1.9067599354717475
Epoch: 12 Loss: 1.7691779234839482
Epoch: 13 Loss: 1.6396014105596235
Epoch: 14 Loss: 1.5169312500219407
Epoch: 15 Loss: 1.3997790473553962
Epoch: 16 Loss: 1.2925410396644528
Epoch: 17 Loss: 1.1953473199018325
Epoch: 18 Loss: 1.1122742553893505
Epoch: 19 Loss: 1.0430018545320117
Epoch: 20 Loss: 0.9865429679359282
Epoch: 21 Loss: 0.9413470213028128
Epoch: 22 Loss: 0.9055221365094386
Epoch: 23 Loss: 0.8771089921900048
Epoch: 24 Loss: 0.8543206727959886
Epoch: 25 Loss: 0.8356873903498345
Epoch: 26 Loss: 0.8200950711386088
Epoch: 27 Loss: 0.8067483817425565
Epoch: 28 Loss: 0.7951006203000794
Epoch: 29 Loss: 0.7847820110041054

In [89]:
model.bias

tensor([-0.5210], dtype=torch.float64, requires_grad=True)

In [91]:
#model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6292705535888672
